apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-proxy
  namespace: kinopoisk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-proxy
  template:
    metadata:
      labels:
        app: image-proxy
    spec:
      containers:
        - name: image-proxy
          image: mdwit/image-proxy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: RATE_LIMIT_MAX_REQUESTS
              value: "50"
          envFrom:
            - secretRef:
                name: image-proxy
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: regcred