apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-proxy
  namespace: kinopoisk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-proxy
  template:
    metadata:
      labels:
        app: image-proxy
    spec:
      containers:
        - name: image-proxy
          image: mdwit/image-proxy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: image-proxy
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      imagePullSecrets:
        - name: regcred