name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Install Swagger
        run: |
          go get -u github.com/swaggo/swag/cmd/swag 2>/dev/null
          go install github.com/swaggo/swag/cmd/swag@latest
      - name: Generate Swagger Documentation
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          swag fmt
          swag init --parseDependency --parseInternal --parseDepth 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mdwit/image-proxy:latest
